download-external-modules: False
evaluate-variables: true
directory:
- ./
framework:
- terraform
skip-check:
- CKV2_GCP*
- CKV_AZURE*
- CKV2_AZURE*
summary-position: bottom
output: 'cli'
compact: True
quiet: True